#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);

templates2events("/etc/ejabberd/ejabberd.cfg",  qw(
	console-save
	bootstrap-console-save
	ejabberd-update
	));

templates2events("/etc/ejabberd/ejabberd.pem",  qw(
        console-save
        bootstrap-console-save
	ejabberd-update
        ));


# not really good setting of logrotate before starting ejabberd
# but works for contrib or core integration
templates2events("/etc/logrotate.d/ejabberd", "ejabberd-update");
templates2events("/etc/httpd/conf/httpd.conf", "ejabberd-update");


#--------------------------------------------------
# pre-backup actions
#--------------------------------------------------
my $event = "pre-backup";

event_link("ejabberd-delete-dumped-tables", $event, "11");
event_link("ejabberd-dump-tables", $event, "21");

foreach $event (qw(
    network-create
    network-delete
    console-save
    ejabberd-update
))
{
    safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/ejabberd");
}

#--------------------------------------------------
# startup and stop symlink
#--------------------------------------------------
service_link_enhanced("ejabberd", "S90", "7");
service_link_enhanced("ejabberd", "K25", "6");
service_link_enhanced("ejabberd", "K25", "1");
service_link_enhanced("ejabberd", "K25", "0");


templates2events("/etc/rc.d/init.d/masq", "ejabberd-update");
safe_symlink("adjust", "root/etc/e-smith/events/ejabberd-update/services2adjust/masq");
safe_symlink("restart", "root/etc/e-smith/events/ejabberd-update/services2adjust/httpd-e-smith");

exit;
