#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

# Test if the service is running before to restore
/usr/bin/systemctl is-active --quiet ejabberd

if [[ $? -eq 0 ]]; then
    if [ -f /var/lib/nethserver/ejabberd/ejabberd.backup ]; then
        /opt/ejabberd-*/bin/ejabberdctl install_fallback /var/lib/nethserver/ejabberd/ejabberd.backup >/dev/null
    else
        echo 'The backup file is not available, restore is not possible'
        exit 0
    fi
fi

if [[ $? -ne 0 ]]; then
    echo 'Ejabberd is not running, restore is not possible'
    exit 0
fi
