#!/usr/bin/perl -w
#
#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#
package esmith;

use strict;
use esmith::event;

my $event = shift || die "Event name arg missing\n";
my $groupName = shift;
my $errors = 0;

if ($groupName ne 'jabberadmins' ) {
    exit(0);
}

if( ! esmith::event::event_signal('nethserver-ejabberd-save')) {
    $errors++;
}

exit($errors == 0 ? 0 : 1);
