#!/usr/bin/perl
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use NethServer::Service;
use NethServer::Directory;
use esmith::AccountsDB;
use esmith::event;
use User::pwent;


my $ldap = NethServer::Directory->new();
my $exitCode = 0;

# Register ejabberd service account in LDAP:
$ldap->configServiceAccount('ejabberd', NethServer::Directory::FIELDS_READ) || $exitCode++;

# Add ejabberd service 
NethServer::Service::manage_add('nethserver-ejabberd', 'ejabberd');


# Add ejabber admin group: jabberadmins
my $group = 'jabberadmins';
if( ! getgrnam($group)) {
    event_signal('group-create', $group) || $exitCode++;
}

exit($exitCode);

