#!/usr/bin/perl -w
#
#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#
package esmith;

use strict;
use Errno;
use esmith::templates;
use esmith::util;
use NethServer::Service;


my $event = shift || die "Event name arg missing\n";

# multiple group name arguments are allowed for
# backward-compatibility, but produce a warning.
my @groups = @ARGV;

foreach my $groupName (@groups)
{
    if ( $groupName eq 'jabberdadmins' ) {
        processTemplate({ TEMPLATE_PATH => '/etc/ejabberd/ejabberd.cfg' });
        if (NethServer::Service::is_enabled('ejabberd')) {
            esmith::util::serviceControl
            (
                NAME   => 'ejabberd',
                ACTION => 'restart',
                BACKGROUND => 'false',
            )
       }

    }

}

